server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: root
    password: Anil101828@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey
